name: CI/CD

on:
  push:
    branches: [development, staging, master]

jobs:
  ci_cd:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Node setup
        uses: actions/setup-node@v1
        with:
          node-version: 12

      - name: Configure AWS
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.DEV_AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.DEV_AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Npm Install
        run: npm ci
        env:
          NPM_TOKEN: ${{secrets.NPM_AUTH_TOKEN}}

      - name: Deploy Serverless
        run: |
          "${GITHUB_WORKSPACE}"/scripts/dep_sls.sh dev
